"""Generate synthetic local AI system inventory records."""

from ai_governance_platform.inventory.schema import AISystemRecord


def generate_sample_inventory() -> list[AISystemRecord]:
    """Return deterministic synthetic inventory records for local development."""
    records = [
        {
            "system_id": "AI-001",
            "system_name": "Retail GenAI Shopping Assistant",
            "system_type": "genai_llm",
            "model_family": "foundation-model-rag",
            "owner": "Maya Chen",
            "business_unit": "Digital Commerce",
            "business_use_case": "Personalized shopping guidance for product discovery",
            "risk_tier": "high",
            "lifecycle_status": "production",
            "deployment_environment": "production",
            "data_sensitivity": "confidential",
            "input_data_type": "customer queries and product catalogue metadata",
            "output_type": "natural language recommendations",
            "aws_service_owner": "AI Platform Team",
            "primary_aws_services": ["Bedrock", "S3", "CloudWatch", "IAM"],
            "approval_status": "approved",
            "monitoring_status": "production_ready",
            "model_card_status": "complete",
            "access_review_status": "complete",
            "incident_process_status": "tested",
            "cost_center": "CC-ECOM-220",
            "created_date": "2025-01-15",
            "last_review_date": "2026-05-10",
        },
        {
            "system_id": "AI-002",
            "system_name": "Talent Acquisition Candidate Assessment Model",
            "system_type": "traditional_ml",
            "model_family": "gradient-boosted-classifier",
            "owner": "Oliver Grant",
            "business_unit": "People Operations",
            "business_use_case": "Candidate screening support for recruiting workflows",
            "risk_tier": "critical",
            "lifecycle_status": "validation",
            "deployment_environment": "staging",
            "data_sensitivity": "restricted",
            "input_data_type": "candidate profile and assessment features",
            "output_type": "candidate suitability score",
            "aws_service_owner": "People Analytics",
            "primary_aws_services": ["SageMaker Model Registry", "S3", "AWS Config", "IAM"],
            "approval_status": "pending",
            "monitoring_status": "enhanced",
            "model_card_status": "draft",
            "access_review_status": "in_progress",
            "incident_process_status": "defined",
            "cost_center": "CC-HR-110",
            "created_date": "2025-11-03",
            "last_review_date": "2026-04-22",
        },
        {
            "system_id": "AI-003",
            "system_name": "Platform Health Anomaly Detection",
            "system_type": "anomaly_detection",
            "model_family": "time-series-anomaly-detection",
            "owner": "Nadia Patel",
            "business_unit": "Cloud Operations",
            "business_use_case": "Detect unusual system health patterns in platform telemetry",
            "risk_tier": "medium",
            "lifecycle_status": "production",
            "deployment_environment": "production",
            "data_sensitivity": "internal",
            "input_data_type": "synthetic infrastructure metrics",
            "output_type": "anomaly alert classification",
            "aws_service_owner": "Cloud Operations",
            "primary_aws_services": ["CloudWatch", "EventBridge", "Lambda", "S3"],
            "approval_status": "approved",
            "monitoring_status": "production_ready",
            "model_card_status": "complete",
            "access_review_status": "complete",
            "incident_process_status": "defined",
            "cost_center": "CC-OPS-310",
            "created_date": "2024-09-20",
            "last_review_date": "2026-03-18",
        },
        {
            "system_id": "AI-004",
            "system_name": "Transaction Fraud Risk Detection",
            "system_type": "traditional_ml",
            "model_family": "ensemble-risk-model",
            "owner": "Ethan Brooks",
            "business_unit": "Risk Management",
            "business_use_case": "Identify potentially fraudulent transaction patterns",
            "risk_tier": "critical",
            "lifecycle_status": "production",
            "deployment_environment": "production",
            "data_sensitivity": "restricted",
            "input_data_type": "transaction and account behavior features",
            "output_type": "fraud risk score",
            "aws_service_owner": "Risk Platform",
            "primary_aws_services": ["SageMaker Model Registry", "DynamoDB", "CloudWatch", "IAM"],
            "approval_status": "approved",
            "monitoring_status": "production_ready",
            "model_card_status": "complete",
            "access_review_status": "overdue",
            "incident_process_status": "not_defined",
            "cost_center": "CC-RISK-410",
            "created_date": "2024-06-12",
            "last_review_date": "2026-02-04",
        },
        {
            "system_id": "AI-005",
            "system_name": "Personalized Product Recommendation Engine",
            "system_type": "recommendation_system",
            "model_family": "collaborative-filtering-ranking",
            "owner": "Priya Nair",
            "business_unit": "Digital Commerce",
            "business_use_case": "Rank product recommendations across web and mobile channels",
            "risk_tier": "medium",
            "lifecycle_status": "approved",
            "deployment_environment": "staging",
            "data_sensitivity": "confidential",
            "input_data_type": "synthetic interaction and catalogue features",
            "output_type": "ranked product list",
            "aws_service_owner": "Personalization Team",
            "primary_aws_services": ["SageMaker Model Registry", "S3", "CloudWatch"],
            "approval_status": "approved",
            "monitoring_status": "enhanced",
            "model_card_status": "draft",
            "access_review_status": "in_progress",
            "incident_process_status": "defined",
            "cost_center": "CC-ECOM-225",
            "created_date": "2025-03-08",
            "last_review_date": "2026-04-08",
        },
        {
            "system_id": "AI-006",
            "system_name": "Customer Support GenAI Chatbot",
            "system_type": "genai_llm",
            "model_family": "retrieval-augmented-llm",
            "owner": "Lucas Rivera",
            "business_unit": "Customer Experience",
            "business_use_case": "Draft support responses using approved knowledge articles",
            "risk_tier": "high",
            "lifecycle_status": "validation",
            "deployment_environment": "test",
            "data_sensitivity": "confidential",
            "input_data_type": "support ticket summaries and knowledge base excerpts",
            "output_type": "draft support response",
            "aws_service_owner": "Customer AI Enablement",
            "primary_aws_services": ["Bedrock", "S3", "CloudWatch", "AWS Config"],
            "approval_status": "pending",
            "monitoring_status": "basic",
            "model_card_status": "draft",
            "access_review_status": "not_started",
            "incident_process_status": "not_defined",
            "cost_center": "CC-CX-515",
            "created_date": "2026-01-10",
            "last_review_date": "2026-05-12",
        },
        {
            "system_id": "AI-007",
            "system_name": "Multimodal Product Search",
            "system_type": "multimodal_ai",
            "model_family": "text-image-embedding-search",
            "owner": "Hannah Wright",
            "business_unit": "Digital Commerce",
            "business_use_case": "Search product catalogue using text and image inputs",
            "risk_tier": "medium",
            "lifecycle_status": "experimental",
            "deployment_environment": "dev",
            "data_sensitivity": "internal",
            "input_data_type": "synthetic text queries and product images",
            "output_type": "matched product results",
            "aws_service_owner": "Search Platform",
            "primary_aws_services": ["Bedrock", "S3", "Lambda", "DynamoDB"],
            "approval_status": "not_required",
            "monitoring_status": "not_enabled",
            "model_card_status": "missing",
            "access_review_status": "not_started",
            "incident_process_status": "not_defined",
            "cost_center": "CC-SEARCH-150",
            "created_date": "2026-02-14",
            "last_review_date": "2026-02-28",
        },
        {
            "system_id": "AI-008",
            "system_name": "AI Platform Cost Anomaly Detection",
            "system_type": "anomaly_detection",
            "model_family": "cost-variance-detector",
            "owner": "Samira Ahmed",
            "business_unit": "Finance Operations",
            "business_use_case": "Identify unusual spend patterns in AI platform cost categories",
            "risk_tier": "medium",
            "lifecycle_status": "approved",
            "deployment_environment": "staging",
            "data_sensitivity": "internal",
            "input_data_type": "synthetic cost and usage aggregates",
            "output_type": "cost anomaly alert",
            "aws_service_owner": "FinOps",
            "primary_aws_services": ["Cost Explorer", "Budgets", "EventBridge", "CloudWatch"],
            "approval_status": "approved",
            "monitoring_status": "enhanced",
            "model_card_status": "complete",
            "access_review_status": "complete",
            "incident_process_status": "defined",
            "cost_center": "CC-FINOPS-700",
            "created_date": "2025-07-19",
            "last_review_date": "2026-04-30",
        },
        {
            "system_id": "AI-009",
            "system_name": "Demand Forecasting Model",
            "system_type": "traditional_ml",
            "model_family": "time-series-forecasting",
            "owner": "Grace Morgan",
            "business_unit": "Supply Chain",
            "business_use_case": "Forecast product demand for inventory planning",
            "risk_tier": "high",
            "lifecycle_status": "production",
            "deployment_environment": "production",
            "data_sensitivity": "confidential",
            "input_data_type": "synthetic sales and operations planning features",
            "output_type": "demand forecast",
            "aws_service_owner": "Supply Chain Analytics",
            "primary_aws_services": ["SageMaker Model Registry", "S3", "CloudWatch", "QuickSight"],
            "approval_status": "approved",
            "monitoring_status": "production_ready",
            "model_card_status": "complete",
            "access_review_status": "complete",
            "incident_process_status": "defined",
            "cost_center": "CC-SC-610",
            "created_date": "2024-12-02",
            "last_review_date": "2026-05-01",
        },
        {
            "system_id": "AI-010",
            "system_name": "Responsible AI Evaluation Workflow",
            "system_type": "genai_llm",
            "model_family": "llm-evaluation-workflow",
            "owner": "Daniel Kim",
            "business_unit": "AI Governance",
            "business_use_case": "Evaluate GenAI outputs for policy, safety, and quality signals",
            "risk_tier": "high",
            "lifecycle_status": "validation",
            "deployment_environment": "local",
            "data_sensitivity": "internal",
            "input_data_type": "synthetic prompts and generated responses",
            "output_type": "responsible AI evaluation summary",
            "aws_service_owner": "AI Governance Office",
            "primary_aws_services": ["Bedrock", "Step Functions", "Lambda", "S3"],
            "approval_status": "pending",
            "monitoring_status": "basic",
            "model_card_status": "draft",
            "access_review_status": "in_progress",
            "incident_process_status": "defined",
            "cost_center": "CC-GOV-900",
            "created_date": "2026-03-05",
            "last_review_date": "2026-05-20",
        },
    ]

    return [AISystemRecord.model_validate(record) for record in records]
