"""Generate synthetic IAM-style access records for AI systems."""

from ai_governance_platform.access_review.schema import AccessRecord
from ai_governance_platform.inventory.generate_inventory import generate_sample_inventory


def generate_sample_access_records() -> list[AccessRecord]:
    """Return deterministic synthetic access records for local access review."""
    systems = {record.system_id: record for record in generate_sample_inventory()}
    records = [
        {
            "access_id": "AR-001",
            "system_id": "AI-001",
            "principal_id": "USR-1001",
            "principal_name": "Maya Chen",
            "principal_type": "user",
            "role_name": "SystemOwner",
            "access_level": "owner",
            "environment": "production",
            "business_justification": "Accountable owner for production GenAI assistant.",
            "access_status": "active",
            "last_review_date": "2026-04-15",
            "expiry_date": "2026-12-31",
            "mfa_enabled": True,
            "privileged_access": True,
            "service_role": False,
        },
        {
            "access_id": "AR-002",
            "system_id": "AI-001",
            "principal_id": "SRV-2001",
            "principal_name": "retail-assistant-runtime-role",
            "principal_type": "service_role",
            "role_name": "BedrockRuntimeRole",
            "access_level": "operator",
            "environment": "production",
            "business_justification": "Runtime service role for synthetic Bedrock invocation path.",
            "access_status": "active",
            "last_review_date": "2026-03-22",
            "expiry_date": "2027-01-31",
            "mfa_enabled": True,
            "privileged_access": False,
            "service_role": True,
        },
        {
            "access_id": "AR-003",
            "system_id": "AI-002",
            "principal_id": "GRP-3001",
            "principal_name": "people-analytics-reviewers",
            "principal_type": "group",
            "role_name": "ModelReviewer",
            "access_level": "analyst",
            "environment": "staging",
            "business_justification": "Review candidate assessment validation outcomes.",
            "access_status": "active",
            "last_review_date": "2026-04-20",
            "expiry_date": "2026-09-30",
            "mfa_enabled": True,
            "privileged_access": False,
            "service_role": False,
        },
        {
            "access_id": "AR-004",
            "system_id": "AI-004",
            "principal_id": "USR-1004",
            "principal_name": "Temporary Admin",
            "principal_type": "user",
            "role_name": "ProductionAdmin",
            "access_level": "admin",
            "environment": "production",
            "business_justification": "temporary",
            "access_status": "active",
            "last_review_date": "2025-03-01",
            "expiry_date": "2026-11-30",
            "mfa_enabled": False,
            "privileged_access": True,
            "service_role": False,
        },
        {
            "access_id": "AR-005",
            "system_id": "AI-004",
            "principal_id": "USR-1005",
            "principal_name": "Former Risk Analyst",
            "principal_type": "user",
            "role_name": "FraudRiskAnalyst",
            "access_level": "analyst",
            "environment": "production",
            "business_justification": "Previous fraud review support assignment.",
            "access_status": "expired",
            "last_review_date": "2024-11-12",
            "expiry_date": "2025-12-31",
            "mfa_enabled": True,
            "privileged_access": False,
            "service_role": False,
        },
        {
            "access_id": "AR-006",
            "system_id": "AI-006",
            "principal_id": "APP-4001",
            "principal_name": "support-chatbot-test-client",
            "principal_type": "application",
            "role_name": "TestInvoker",
            "access_level": "developer",
            "environment": "test",
            "business_justification": "Integration test client for chatbot validation.",
            "access_status": "active",
            "last_review_date": "2026-05-01",
            "expiry_date": "2026-08-31",
            "mfa_enabled": True,
            "privileged_access": False,
            "service_role": False,
        },
        {
            "access_id": "AR-007",
            "system_id": "AI-007",
            "principal_id": "USR-1007",
            "principal_name": "Search Data Scientist",
            "principal_type": "user",
            "role_name": "ExperimentDeveloper",
            "access_level": "developer",
            "environment": "dev",
            "business_justification": "Develop multimodal search prototype with synthetic inputs.",
            "access_status": "active",
            "last_review_date": "2026-05-10",
            "expiry_date": "2026-10-31",
            "mfa_enabled": True,
            "privileged_access": False,
            "service_role": False,
        },
        {
            "access_id": "AR-008",
            "system_id": "AI-009",
            "principal_id": "USR-1009",
            "principal_name": "Supply Chain Operator",
            "principal_type": "user",
            "role_name": "ProductionOperator",
            "access_level": "operator",
            "environment": "production",
            "business_justification": "Operate production demand forecasting batch review.",
            "access_status": "active",
            "last_review_date": "2026-02-18",
            "expiry_date": "2026-12-31",
            "mfa_enabled": True,
            "privileged_access": True,
            "service_role": False,
        },
        {
            "access_id": "AR-009",
            "system_id": "AI-010",
            "principal_id": "SRV-2010",
            "principal_name": "rai-evaluation-workflow-role",
            "principal_type": "service_role",
            "role_name": "EvaluationWorkflowRole",
            "access_level": "operator",
            "environment": "dev",
            "business_justification": "",
            "access_status": "active",
            "last_review_date": "2026-03-01",
            "expiry_date": "2026-09-30",
            "mfa_enabled": True,
            "privileged_access": False,
            "service_role": True,
        },
        {
            "access_id": "AR-010",
            "system_id": "AI-008",
            "principal_id": "USR-1010",
            "principal_name": "Finance Reviewer",
            "principal_type": "user",
            "role_name": "CostReadOnly",
            "access_level": "read_only",
            "environment": "staging",
            "business_justification": "Review synthetic AI platform cost anomaly outputs.",
            "access_status": "pending_removal",
            "last_review_date": "2026-01-20",
            "expiry_date": "2026-07-31",
            "mfa_enabled": True,
            "privileged_access": False,
            "service_role": False,
        },
        {
            "access_id": "AR-011",
            "system_id": "AI-003",
            "principal_id": "SRV-2003",
            "principal_name": "health-monitoring-metrics-role",
            "principal_type": "service_role",
            "role_name": "CloudWatchMetricsReader",
            "access_level": "read_only",
            "environment": "production",
            "business_justification": "Read synthetic metrics for anomaly detection pipeline.",
            "access_status": "active",
            "last_review_date": "2026-03-12",
            "expiry_date": "2027-03-12",
            "mfa_enabled": True,
            "privileged_access": False,
            "service_role": True,
        },
        {
            "access_id": "AR-012",
            "system_id": "AI-005",
            "principal_id": "USR-1012",
            "principal_name": "Personalization Analyst",
            "principal_type": "user",
            "role_name": "RecommendationAnalyst",
            "access_level": "analyst",
            "environment": "staging",
            "business_justification": "Analyze recommendation quality metrics.",
            "access_status": "revoked",
            "last_review_date": "2026-04-02",
            "expiry_date": "2026-05-15",
            "mfa_enabled": True,
            "privileged_access": False,
            "service_role": False,
        },
    ]

    return [
        AccessRecord.model_validate(
            {
                **record,
                "system_name": systems[record["system_id"]].system_name,
            }
        )
        for record in records
    ]
